import Head from "next/head";
import Departments from "../components/departments/Departments";
import Footer from "../components/footer/Footer";
import GalleryContainer from "../components/gallery/GalleryContainer";
import Header from "../components/header/Header";
import Hero from "../components/hero/Hero";
import Instalations from "../components/instalations/Instalations";
import Reviews from "../components/reviews/Reviews";
import Slider from "../components/slider/Slider";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="contenedor">
        <Header />
        <Hero />
        <Departments/>
        <Slider />
        <Instalations />
        <GalleryContainer/>
        <Reviews/>
        <Footer/>
      </div>
    </>
  );
}
